# Generated by Django 2.2.7 on 2019-12-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('Name', models.TextField()),
                ('is_verified', models.CharField(max_length=15)),
                ('is_following', models.CharField(max_length=25)),
                ('page_url', models.TextField()),
            ],
        ),
    ]
